version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-domain"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w2jug55smjyz"
s3_prefix = "sam-domain"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentTagName=\"qa\" EnvConfigdomainAsString=\"/<EnvironmentName>/domain\" EnvConfigvalidationDomainAsString=\"/<EnvironmentName>/validationDomain\""

